This is the homework for week 2! The prompt is to use NumPy (or sagemath) to determine if a list of vectors forms an orthogonal / orthonormal basis for a vector space, compute inner products, multiply matrices, and compute LU and spectral decompositions.

Problem 1: Build a function to take two vectors with real-valued entries and compute their inner product. 

In [4]:
def ip(v1,v2):
    ip_out = 0 

    # ip out is the running sum of our terms
    for i in range(len(v1)):
        # this line computes ith sum in our inner product calculation
        ip_out = ip_out + v1[i]*v2[i]
    
    #the reutrn statement ends the function and outputs the inner product of both vectors
    return ip_out 

#put test cases here
a = [1,2,3,-1]
b = [-2,1,1,3]

#print the output
print(f'The inner product of {a} and {b} is {ip(a,b)}')

The inner product of [1, 2, 3, -1] and [-2, 1, 1, 3] is 0


Problem 2: Build a function which checks if two matrices can be multiplied and then multiplies them.

In [5]:
import numpy as np

A = np.array( [ [3,2], [-1,0]] )
B = np.array( [ [3,2], [-1,0]] )

def canMult(A,B):
    if np.shape(A)[1] == np.shape(A)[0]:
        return True
    else:
        return False

#multiply the matrices    
def mult(A,B):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    r = np.shape(B)[1]
    sh = (m,r)

    C = np.zeros(sh)
    if canMult(A,B) is True:
        for i in range(np.shape(B)[1]): 
            for j in range(m):
                C[j,i] = ip(A[j,:],B[:,i])
                
        return C 
    else:
        return print('Cannot multiply these matrices')

mult(A,B)

array([[ 7.,  6.],
       [-3., -2.]])

Problem 3: Build a function which takes A and computes $A^T$.

In [4]:
import numpy as np

def transpose(A):
    """Return the transpose of matrix A."""
    return np.transpose(A)

# Example test
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original A:\n", A)
print("Transpose of A:\n", transpose(A))



Original A:
 [[1 2 3]
 [4 5 6]]
Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


Problem 4: Build a function which determines if a list of vectors is an orthogonal or orthonormal basis by computing $A^T A$ and checking if it is diagonal / I. (Hint: Use your function from problem 3!)

In [5]:
def check_basis(vectors):
    """Check if a list of vectors is orthogonal or orthonormal."""
    A = np.array(vectors).T
    gram = transpose(A) @ A
    
    if np.allclose(gram, np.eye(gram.shape[0])):
        return "Orthonormal basis"
    elif np.allclose(gram, np.diag(np.diag(gram))):
        return "Orthogonal basis"
    else:
        return "Not orthogonal"

# Example tests
vectors1 = [[1, 0], [0, 1]]  # standard basis in R^2
vectors2 = [[1, 0], [1, 1]]  # not orthogonal

print("Vectors1:", check_basis(vectors1))
print("Vectors2:", check_basis(vectors2))



Vectors1: Orthonormal basis
Vectors2: Not orthogonal


Problem 5: Use Numpy's internal tools to compute the eigenvectors and eigenvalues of A, and then build a function which outputs the spectral decomposition of A.

In [6]:
def spectral_decomposition(A):
    """Return the spectral decomposition of matrix A."""
    vals, vecs = np.linalg.eig(A)
    # Reconstruct A from spectral decomposition: A = V Λ V^{-1}
    Lambda = np.diag(vals)
    V = vecs
    V_inv = np.linalg.inv(V)
    return V, Lambda, V_inv

# Example test
A = np.array([[4, 1],
              [2, 3]])
V, Lambda, V_inv = spectral_decomposition(A)
print("Eigenvectors (V):\n", V)
print("Eigenvalues (Lambda):\n", Lambda)
print("Check reconstruction (V Λ V^-1):\n", V @ Lambda @ V_inv)



Eigenvectors (V):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
Eigenvalues (Lambda):
 [[5. 0.]
 [0. 2.]]
Check reconstruction (V Λ V^-1):
 [[4. 1.]
 [2. 3.]]
